name: Music Launch Hub
favicon: null
layout_spectrum: 0.0330760576762259
typography_spectrum: 0.31258594733662903
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7596835258882493
  lightness: 0.009515341138467193
  saturation: 0.6062547860201448
  rhythmicContrast: 0.6350968694314361
purpose: []
